# Generated by Django 2.1.7 on 2019-05-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=' ', max_length=20)),
                ('firstName', models.CharField(default=' ', max_length=20)),
                ('lastName', models.CharField(default=' ', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('homePhone', models.CharField(default='', max_length=12)),
                ('title', models.IntegerField(default=0)),
                ('address', models.CharField(default=' ', max_length=30)),
                ('city', models.CharField(default=' ', max_length=20)),
                ('state', models.CharField(default=' ', max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
                ('officeNumber', models.IntegerField(default=0)),
                ('officePhone', models.CharField(default='', max_length=12)),
                ('officeDays', models.CharField(default=' ', max_length=10)),
                ('officeHoursStart', models.IntegerField(default=0)),
                ('officeHoursEnd', models.IntegerField(default=0)),
                ('currentUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('onCampus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('meetingDays', models.CharField(default=' ', max_length=10)),
                ('startTime', models.IntegerField(default=0)),
                ('endTime', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.Course')),
            ],
        ),
        migrations.AddField(
            model_name='accountsection',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Section'),
        ),
    ]
