# Generated by Django 2.1.7 on 2019-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.IntegerField(),
        ),
    ]
