# Generated by Django 2.1.7 on 2019-04-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190422_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='officeHoursEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='officeHoursStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='officeNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='zipCode',
            field=models.IntegerField(default=0),
        ),
    ]
