# Generated by Django 2.1.7 on 2019-05-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190422_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classDays',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classHoursEnd',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classHoursStart',
        ),
    ]
