# Generated by Django 2.1.7 on 2019-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190416_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
