# Generated by Django 2.1.7 on 2019-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20190416_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='homePhone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='officePhone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
